artifacts_root: artifacts

#Here we created an artifacts folder and within we create dta_ingestion folder am
#source url- github url and the downloaded zip file as local_data_file and the unzip file 
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rajalakshmibharath/Precision_Agriculture/raw/master/data/beetroot.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


  